"""v0.9.3 wire-up: screenshots + sample-output README + version bump + CHANGELOG."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# 1. README
p = ROOT / "README.md"
s = p.read_text(encoding="utf-8")

old1 = "AgentSuite is a Python package and MCP server."
new1 = "![AgentSuite founder run](docs/screenshots/cli-founder-run.svg)\n\nAgentSuite is a Python package and MCP server."
assert old1 in s
s = s.replace(old1, new1, 1)

s = s.replace("**v0.9.2**", "**v0.9.3**", 1)

anchor = "## Architecture"
if anchor in s:
    add_block = (
        "## Screenshots and sample output\n\n"
        "| | |\n|---|---|\n"
        "| ![cli](docs/screenshots/cli-founder-run.svg) | A real `agentsuite founder run` end-to-end. Five stages, JSON summary. |\n"
        "| ![tree](docs/screenshots/runs-tree.svg) | The 14-artifact run directory after success. |\n"
        "| ![brand](docs/screenshots/brand-system-rendered.svg) | `brand-system.md` rendered. |\n"
        "| ![qa](docs/screenshots/qa-report-rendered.svg) | `qa_report.md` rendered. |\n"
        "| ![kernel](docs/screenshots/kernel-tree.svg) | `_kernel/<project_slug>/` after approval. |\n\n"
        "Browse a complete sample run on GitHub at [`examples/sample-output/founder/`](examples/sample-output/founder/) "
        "— every artifact a real Founder run produces, no install required.\n\n"
    )
    s = s.replace(anchor, add_block + anchor, 1)
else:
    print("WARN README anchor missing")
p.write_text(s, encoding="utf-8")
print("README updated")

# 2. docs/index.html
p = ROOT / "docs" / "index.html"
s = p.read_text(encoding="utf-8")
s = s.replace('<span class="v">v0.9.2</span>', '<span class="v">v0.9.3</span>', 1)

old_sample = (
    '  <section class="output-example">\n'
    '    <h2>Sample Output</h2>\n'
    '    <pre><code>$ agentsuite founder --company-name "Acme Corp" --industry "SaaS" --stage "seed"\n\n'
    '✔ Intake complete\n'
    '✔ Context extracted\n'
    '✔ Spec generated (9 artifacts)\n'
    '✔ Execute complete\n'
    '✔ QA passed — score 8.3/10\n\n'
    'Artifacts written to .agentsuite/founder-2026-04-27/\n'
    '  brand-voice.md          2.1 KB\n'
    '  positioning-statement.md  1.4 KB\n'
    '  icp-profile.md          1.8 KB\n'
    '  + 6 more artifacts\n'
    '</code></pre>\n'
    '  </section>'
)
new_sample = (
    '  <section class="output-example">\n'
    '    <h2>Sample run</h2>\n'
    '    <p><img src="screenshots/cli-founder-run.svg" alt="agentsuite founder run end to end" style="max-width:100%;border-radius:6px;border:1px solid var(--border);" /></p>\n'
    '    <p>Browse the full output of a real run — 14 artifacts, no install required — at <a href="https://github.com/scottconverse/AgentSuite/tree/main/examples/sample-output/founder">examples/sample-output/founder/</a>.</p>\n\n'
    '    <h3>What you get on disk</h3>\n'
    '    <p><img src="screenshots/runs-tree.svg" alt="run directory tree after success" style="max-width:100%;border-radius:6px;border:1px solid var(--border);" /></p>\n\n'
    '    <h3>Spec artifacts (rendered)</h3>\n'
    '    <p><img src="screenshots/brand-system-rendered.svg" alt="brand-system.md rendered" style="max-width:100%;border-radius:6px;border:1px solid var(--border);" /></p>\n'
    '    <p><img src="screenshots/qa-report-rendered.svg" alt="qa_report.md rendered" style="max-width:100%;border-radius:6px;border:1px solid var(--border);" /></p>\n\n'
    '    <h3>After approval</h3>\n'
    '    <p><img src="screenshots/kernel-tree.svg" alt="kernel directory after approval" style="max-width:100%;border-radius:6px;border:1px solid var(--border);" /></p>\n'
    '  </section>'
)
assert old_sample in s, "sample anchor missing"
s = s.replace(old_sample, new_sample)
p.write_text(s, encoding="utf-8")
print("index.html updated")

# 3. examples/sample-output/founder/README.md
sample_readme = ROOT / "examples" / "sample-output" / "founder" / "README.md"
sample_readme.write_text(
    "# Sample output — Founder agent (PatentForgeLocal scenario)\n\n"
    "This directory is a **complete, deterministic** Founder run committed to the repo so prospective adopters can browse what AgentSuite produces without installing anything.\n\n"
    "- **Generated by:** `tests/golden/test_founder_patentforgelocal.py` equivalent invocation under the deterministic mock LLM (`agentsuite.llm.mock._default_mock_for_cli`).\n"
    "- **Inputs:** `examples/patentforgelocal/` (project brief + voice sample).\n"
    "- **Reproducible:** Regenerated by the v0.9.3 sample-output script. Bytes are stable from one run to the next under the mock.\n\n"
    "## What's here\n\n"
    "- `_state.json` — the run's persisted kernel state.\n"
    "- `inputs_manifest.json`, `extracted_context.json`, `consistency_report.json`, `cost_summary.json`.\n"
    "- `qa_report.md`, `qa_scores.json` — the QA stage output.\n"
    "- 7 founder spec artifacts (`brand-system.md`, `founder-voice-guide.md`, etc.).\n"
    "- `brief-template-library/` — 8 reusable brief templates for downstream agents.\n"
    "- `TREE.txt` — directory listing for grep convenience.\n\n"
    "This is real Founder output rendered against a fixed prompt template under a deterministic mock — exactly what a live `agentsuite founder run` produces, minus the LLM-specific phrasing on free-text bodies.\n",
    encoding="utf-8",
)
print("sample-output README written")

# 4. Version bumps
bumps = [
    ("pyproject.toml", 'version = "0.9.2"', 'version = "0.9.3"'),
    ("agentsuite/__version__.py", '__version__ = "0.9.2"', '__version__ = "0.9.3"'),
    ("docs/troubleshooting.md", "**Version 0.9.2**", "**Version 0.9.3**"),
    ("docs/troubleshooting.md", "*AgentSuite v0.9.2 — Troubleshooting Guide*", "*AgentSuite v0.9.3 — Troubleshooting Guide*"),
]
for path, old_v, new_v in bumps:
    pp = ROOT / path
    ss = pp.read_text(encoding="utf-8")
    if old_v not in ss:
        print(f"  MISS {path}: {old_v!r}")
        continue
    pp.write_text(ss.replace(old_v, new_v, 1), encoding="utf-8")
    print(f"  bumped {path}")

# 5. CHANGELOG promote
p = ROOT / "CHANGELOG.md"
s = p.read_text(encoding="utf-8")
old = (
    "## [Unreleased]\n\n"
    "### Roadmap\n\n"
    "- **v0.9.3** — Screenshots + committed `examples/sample-output/founder/` fixture (P4).\n"
    "- **v1.0.0-rc1 / v1.0.0** — Compatibility freeze, Discussions seeding, \"Why AgentSuite\" hook, three good-first-issue tickets, signed tags, public launch."
)
new = (
    "## [Unreleased]\n\n"
    "### Roadmap\n\n"
    "- **v1.0.0-rc1 / v1.0.0** — Compatibility freeze, Discussions seeding, \"Why AgentSuite\" hook, three good-first-issue tickets, signed tags, public launch.\n\n"
    "## [0.9.3] - 2026-04-29\n\n"
    "P4 — visual + sample-output release. Replaces the text-only landing\n"
    "experience with rendered terminal SVGs and a committed sample run.\n"
    "No code changes; documentation and assets only.\n\n"
    "### Added\n\n"
    "- **5 SVG screenshots** under `docs/screenshots/` rendered programmatically via `rich.Console.save_svg()`: `cli-founder-run.svg`, `runs-tree.svg`, `brand-system-rendered.svg`, `qa-report-rendered.svg`, `kernel-tree.svg`. Reproducible from the sample-output and `scripts/_v093_wire.py` invocation in the v0.9.3 dev report.\n"
    "- **`examples/sample-output/founder/`** — a complete, browsable Founder run committed to the repo (29 files: state + inputs + extracted context + cost + QA + 7 spec artifacts + 8 brief templates + TREE.txt). Generated under the deterministic mock LLM so adopters can preview real output without installing AgentSuite.\n"
    "- **Hero screenshot** in `README.md` above the install block, plus a \"Screenshots and sample output\" section linking the rendered SVGs and the committed sample run.\n"
    "- **`docs/index.html`** sample section now embeds the cli, runs-tree, brand-system, qa-report, and kernel-tree SVGs in place of the text-only mock output.\n\n"
    "### Deferred\n\n"
    "- The 6th planned screenshot — `mcp-tool-list-claude-code.png` showing AgentSuite tools surfaced inside Claude Code — needs a real Claude Code session and is left for a hand capture in the next minor."
)
assert old in s, "CHANGELOG anchor missing"
p.write_text(s.replace(old, new), encoding="utf-8")
print("CHANGELOG promoted")

print("DONE")
